### ISSUE TITLE
Java Student Management System Project

### ISSUE THREAD

**Issue by brodzy** [brodzy/java#23]
**Overview**:
This project is designed to help you practice the basics of Java programming, including classes, methods, and loops. You'll create a simple "Student Management System" that allows you to add and display student information.

**Project Requirements**:

1. Create a Java program that consists of two classes: `Student` and `StudentManagementSystem`.
   
2. The `Student` class should have the following attributes:
   - `name` (String)
   - `age` (int)
   - `grade` (double)

3. Implement a constructor in the `Student` class to initialize these attributes.

4. Add a method in the `Student` class called `display` that prints out the student's name, age, and grade.

5. In the `StudentManagementSystem` class's `main` method, create an array or ArrayList of `Student` objects.

6. Use a loop to input information for at least five students (name, age, and grade) from the user.

7. Store each student's information in a `Student` object and add it to the array or ArrayList.

8. After inputting all the student data, use another loop to display the information of all the students.

**Example Output**:

```
Student Information:
Name: John
Age: 18
Grade: 85.5

Name: Sarah
Age: 19
Grade: 92.0

... (for each student)
```

**Submission**:
Please create a GitHub repository for this project and commit your code to it. You can organize your project directory as you see fit. Provide a link to your GitHub repository when you're done.

Feel free to ask if you have any questions or need clarification. Happy coding!

---

**Comment by Abhinavagarwa** [comment]
hey @brodzy can you please assign me this under hacktober2023
